name: Generate Rider Data

on:
  workflow_dispatch:
    inputs:
      rider_id:
        description: 'ZwiftPower rider id'
        required: true
        type: string

permissions:
  contents: write
  id-token: write

jobs:
  build-and-generate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data manager CLI
        run: |
          python -m zwift_api_client.utils.data_manager_cli --refresh-rider ${{ inputs.rider_id }} --yes

      - name: Copy generated JSON to public data folder
        run: |
          mkdir -p public/data/riders/${{ inputs.rider_id }}
          if [ -d zwift_api_client/data/riders/${{ inputs.rider_id }} ]; then
            cp -v zwift_api_client/data/riders/${{ inputs.rider_id }}/*.json public/data/riders/${{ inputs.rider_id }}/ || true
          else
            echo "No generated data found for ${{ inputs.rider_id }}"
          fi

      - name: Commit and push generated files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/data/riders/${{ inputs.rider_id }} || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: add/update generated rider data for ${{ inputs.rider_id }}"
            git push origin HEAD:${{ github.ref_name }}
          fi
