name: CI & Railway Deploy

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: Install & Integration Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run integration test (optional)
        env:
          ZWIFT_EMAIL: ${{ secrets.ZWIFT_EMAIL }}
          ZWIFT_PASSWORD: ${{ secrets.ZWIFT_PASSWORD }}
          TEST_RIDER_ID: ${{ secrets.TEST_RIDER_ID }}
        run: |
          if [ -n "${TEST_RIDER_ID}" ]; then
            echo "Running integration test for rider ${TEST_RIDER_ID}"
            python -m zwift_api_client.utils.data_manager_cli --refresh-rider "${TEST_RIDER_ID}" --yes
          else
            echo "TEST_RIDER_ID not set; skipping integration test"
          fi

  deploy:
    name: Deploy to Railway (optional)
    runs-on: ubuntu-latest
    needs: test
    if: ${{ secrets.RAILWAY_TOKEN != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: |
          curl -sSL https://raw.githubusercontent.com/railwayapp/cli/master/install.sh | sh || true
          # If the above fails, try npm install
          if ! command -v railway >/dev/null 2>&1; then
            npm i -g @railway/cli || true
          fi

      - name: Login to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway login --token "$RAILWAY_TOKEN"

      - name: Deploy to Railway
        run: |
          # Deploy current branch/service to Railway
          railway up --yes || echo "railway up failed; check logs"
